export const DEFAULT_WIDGETS = [
	{
		id: "kpi-summary",
		type: "kpi-cards",
		title: "Key Metrics",
		dataSource: "/api/v1/reports/kpi-summary",
		layout: { x: 0, y: 0, w: 12, h: 2 },
		chartConfig: {},
	},
	{
		id: "pipeline-funnel",
		type: "funnel",
		title: "Sales Pipeline",
		dataSource: "/api/v1/deals/reports/pipeline-funnel",
		layout: { x: 0, y: 2, w: 6, h: 4 },
		chartConfig: { chartType: "bar", colorScheme: "blue" },
	},
	{
		id: "revenue-forecast",
		type: "forecast",
		title: "Revenue Forecast",
		dataSource: "/api/v1/deals/reports/revenue-forecast",
		layout: { x: 6, y: 2, w: 6, h: 4 },
		chartConfig: { chartType: "area", colorScheme: "green" },
	},
	{
		id: "win-loss",
		type: "comparison",
		title: "Win/Loss Ratio",
		dataSource: "/api/v1/deals/reports/win-loss",
		layout: { x: 0, y: 6, w: 4, h: 4 },
		chartConfig: { chartType: "pie" },
	},
	{
		id: "activity-by-type",
		type: "breakdown",
		title: "Activities by Type",
		dataSource: "/api/v1/activities/reports/by-type",
		layout: { x: 4, y: 6, w: 4, h: 4 },
		chartConfig: { chartType: "donut" },
	},
	{
		id: "contact-growth",
		type: "trend",
		title: "Contact Growth",
		dataSource: "/api/v1/contacts/reports/growth",
		layout: { x: 8, y: 6, w: 4, h: 4 },
		chartConfig: { chartType: "line", showArea: true },
	},
];
